services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: article-service/Dockerfile
    restart: "no"
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
      - posts-db
      - kc-db
    networks:
      - app

  posts-db:
    container_name: posts-db
    image: postgres:16-alpine3.21
    ports:
      - "5432:5432"
    volumes:
      - posts-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: posts
    networks:
      - app

  kc-db:
    container_name: keycloak-db
    image: postgres:16-alpine3.21
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keycloak
    volumes:
      - kc_data:/var/lib/postgresql/data
    ports:
      - "5435:5435"
    networks:
      - keycloak-network
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.1.3
    ports:
      - "9080:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: kc-db
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: ./keycloak/imports
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import
    networks:
      - keycloak-network
    depends_on:
      - kc-db
    command:
      - "start-dev"

  minio:
    container_name: "video-streaming-minio"
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_admin

networks:
  app:
    driver: bridge
  keycloak-network:
    driver: bridge

volumes:
  minio-data:
    driver: local
  posts-data:
    driver: local
  kc_data:
    driver: local
  keycloak:
    driver: local