spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger
    username: vay
    password: vay0013
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
#      data-locations: classpath:

