spring:
  datasource:
#    url: jdbc:postgresql://db:5432/messenger?currentSchema=messenger
    url: jdbc:postgresql://localhost:5432/messenger?currentSchema=messenger
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/db.changelog.yml
    enabled: true
    default-schema: messenger
security:
  jwt:
    secret: c2RhbGZiYXNka2JmbHNkaGZ4SkhMSExLSkRBRkFIbmZuZGFpc2xuZmhrZHNham5oZmZmZmZm
    access: 3600000
    refresh: 2592000000
