spring:
  datasource:
    url: jdbc:postgresql://db:5432/messenger
#    url: jdbc:postgresql://localhost:5432/messenger
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true
    properties:
      hibernate:
        format_sql: postgresql
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret:
    key: BOT
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:

